name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mini_credit_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports: ["3307:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with: {bun-version: "1.1.22"}
      - run: bun install
      - run: bunx prisma generate
      - run: bunx prisma migrate deploy
        env:
          DATABASE_URL: mysql://user:password@127.0.0.1:3307/mini_credit_db
      - run: bun test
        env:
          DATABASE_URL: mysql://user:password@127.0.0.1:3307/mini_credit_db
          JWT_SECRET: testsecretjwt
          PORT: 5000
          PRETTY_LOGS: "false"
